defaults:
  - _self_
  - model: small
  - override hydra/launcher: basic # submitit_slurm

ngpus: 1
tokens: 23 # 23 for uniform
num_labels: 2 # prokaryotic (0), eukaryotic (1)

training:
  batch_size: 8
  accum: 1
  n_iters: 1300001
  snapshot_freq: 50000
  log_freq: 50
  eval_freq: 100
  snapshot_freq_for_preemption: 10000
  weight: standard
  snapshot_sampling: True
  ema: 0.9999

data:
  name: IPR036736_90_grouped
  train_path: /work3/s204514/datasets/IPR036736_90_grouped/train
  valid_path: /work3/s204514/datasets/IPR036736_90_grouped/valid
  tokenizer_path: '/zhome/fb/0/155603/axolotl/tokenizer/tokenizer_absorb'
  # train_path: /home/kkj/axolotl/datasets/IPR036736_90_grouped/train
  # valid_path: /home/kkj/axolotl/datasets/IPR036736_90_grouped/valid
  # tokenizer_path: '/home/kkj/axolotl/tokenizer/tokenizer_absorb'

graph:
  type: absorb
  file: data
  report_all: False

noise:
  type: loglinear
  sigma_min: 1e-4
  sigma_max: 20

sampling:
  predictor: euler
  steps: 128
  length: 2048
  noise_removal: True
  cfg: 'testing' # cfg_w = 0 => unconditional. cfg_w = 1 => conditional. 0 < cfg_w < 1 => interpolation. cfg_w > 1 => extrapolation. cfg_w = 'testing' => testing different cfg_w at once
  label: 'random' # one of 'random', 'eukaryotic', 'prokaryotic'. 'random' gives a mix of eukaryotic and prokaryotic labels

eval:
  batch_size: 8
  perplexity: False # True
  perplexity_batch_size: 32

optim:
  weight_decay: 0
  optimizer: AdamW
  lr: 3e-4
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8
  warmup: 2500
  grad_clip: 1.


hydra:
  run:
    dir: exp_local/${data.name}/${now:%Y.%m.%d}/${now:%H%M%S}
    # dir: exp_local/work3/s204514/datasets/IPR036736_90_grouped/train/2025.01.24/113805
  sweep:
    dir: exp/${data.name}/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    # max_num_timeout: 100000
    # # timeout_min: 10079
    # partition: g40x
    # account: stanford
    # mem_gb: 96
    # cpus_per_task: 40
    # gpus_per_node: ${ngpus}
    # constraint: null
    # max_num_timeout: 100000
    # # timeout_min: 10079
    # partition: g40x
    # account: stanford
    # mem_gb: 96
    # cpus_per_task: 40
    # gpus_per_node: ${ngpus}
    # constraint: null
